### ISSUE TITLE
Add list of necessary GH libraries to the readme.md

### ISSUE THREAD

**Issue by dantaeyoung** [dantaeyoung/GrasshopperChallenges#3]

**Comment by danvk** [comment]
This would be appreciated.

I get this error when I open challenge E:
![image](https://user-images.githubusercontent.com/98301/40747024-1e0ee386-642a-11e8-8596-aa7e838eae0a.png)

And this red component which looks like it might be an error?
![image](https://user-images.githubusercontent.com/98301/40747052-2f26cc74-642a-11e8-9158-88c3408ab474.png)

**Comment by dantaeyoung** [comment]
Thanks for your comment! Seriously, very happy to receive feedback, and I really appreciate it.

I added a requirement at the top of the .GHX file:

![image](https://user-images.githubusercontent.com/1616571/40881762-8fe53c56-669d-11e8-9b49-b4af033405a5.png)
and inline as well:
![image](https://user-images.githubusercontent.com/1616571/40881751-28e9b25c-669d-11e8-88a0-7617f86d48d0.png)

**Comment by dantaeyoung** [comment]
@danvk: Regarding the red component, that might be a different error? What do you see when you click on the red speech bubble on the upper right hand corner of the component?

**Comment by danvk** [comment]
![image](https://user-images.githubusercontent.com/98301/40940788-e2f66620-6816-11e8-9546-ca57b1a34146.png)

**Comment by dantaeyoung** [comment]
@danvk - Looks like you're on OSX? This is interesting - I think you're the first person to try the challenges with Grasshopper for Mac.

Unfortunately Grasshopper for Mac is still incompatible with a lot of plugins, including that specific bake component, which relies on C#. You might want to try using a bake component from Human. Could you see if using the "Bake Geometry" component from Human works? 

![image](https://user-images.githubusercontent.com/1616571/40948173-c05a6b8e-6834-11e8-9220-ac6a39ccaedc.png)

**Comment by dantaeyoung** [comment]
This issue should be resolved with Rhino 7's PackageManager's ability to download and install plugins.
