### ISSUE TITLE
Correct despite error on C0

### ISSUE THREAD

**Issue by danvk** [dantaeyoung/GrasshopperChallenges#4]
It says "Correct" but I'm getting an error. So I'm not sure if this is the intended solution or not!

![image](https://user-images.githubusercontent.com/98301/40736830-176af47e-640d-11e8-8742-7e946d324941.png)

**Comment by danvk** [comment]
It looks like the checker is just checking the number of inputs, rather than their contents. They're all null.

**Comment by dantaeyoung** [comment]
Thanks for your issue @danvk ! You're right - I'll add some more requirements for solution checking.

**Comment by dantaeyoung** [comment]
Fixed by c3306b5
